name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      - name: Build Nix Home Manager configuration
        working-directory: ${{ github.workspace }}
        run: ./scripts/install.shF
